server:
  rootPath: /api/*

database:
  user: sa
  password:
  url: jdbc:h2:mem:tests;DB_CLOSE_DELAY=-1
  driverClass: org.h2.Driver

workers:
  - worker: bo.gotthardt.todolist.worker.UsernamePrintWorker
    threads: 1